### ISSUE TITLE
a better onUpgrade implementation

### ISSUE THREAD

**Issue by hehonghui** [spongebobrf/AndroidDatabaseUpgrades#1]
With sql database version number to name the file, and then incremental upgrade. for example, from version 2 to 4, create these upgrade sql file : 

```
  2.sql
  3.sql
  4.sql
```

 onUpgrade method : 

```
   @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        Log.e(TAG, "Updating table from " + oldVersion + " to " + newVersion);
        try {
            for (int i = oldVersion; i < newVersion; ++i) {
                String migrationName = String.valueOf(i));
                Log.d(TAG, "Looking for migration file: " + migrationName);
                readAndExecuteSQLScript(db, context, migrationName);
            }
        } catch (Exception exception) {
            Log.e(TAG, "Exception running upgrade script:", exception);
        }
    }
```

This is a better implementation.

**Comment by riggaroo** [comment]
I disagree. The implementation from my example indicates what version it is coming from and going to, which is far more descriptive. Besides that, your implementation wouldn't work, as you would be on version 2, and then it would run the migration for version 2 which would produce errors.
